name = "ResistanceDistance"
uuid = "6d9c698a-143c-4d19-893a-b951e9cb8478"
authors = ["Jean F Du Plessis"]
version = "1.0.0"

[deps]
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
julia = "1"
Graphs = "1.9.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
